meta_product_name: "Kamizero"
meta_title: "Kamizero - Managing School Notices Paperlessly"
meta_description: "Kamizero makes communication between shools and parents digitally organized and simple to use."
meta_image: "KAMIZERO LOGO MAIN.png" # should exist in `app/assets/images/`
